In [147]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [148]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [149]:


# # Load your 7043 row IBM dataset
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

# # Logical mapping function
def assign_indian_operator(row):
     if row['InternetService'] == 'Fiber optic':
         return 'Reliance Jio'
     elif row['InternetService'] == 'DSL':
         return 'Airtel'
     elif row['PhoneService'] == 'Yes' and row['MultipleLines'] == 'Yes':
         return 'Vodafone Idea'
     else:
         return 'BSNL'

# # Create the column
df['Sim'] = df.apply(assign_indian_operator, axis=1)

In [150]:
df['TotalCharges'] = df['TotalCharges'].replace(" ", np.nan)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])

In [151]:
#handling missing values

df['TotalCharges'].isnull().sum()

np.int64(11)

In [152]:
df['T_MODE'] = df['TotalCharges'].fillna(df['TotalCharges'].mode()[0])
df = df.drop('TotalCharges',axis=1)

In [153]:
df['T_MODE'].isnull().sum()

np.int64(0)

In [154]:
X=df.drop('Churn',axis=1)
y=df['Churn']

In [155]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=45)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  Churn             7043 non-null   object
 20  Sim               7043 non-null   object
 21  T_MODE            7043 non-null   float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.2+ MB

In [157]:
X_train_nums_cols = X_train.select_dtypes(exclude=object)
X_train_cats_cols = X_train.select_dtypes(include=object)

X_test_nums_cols = X_test.select_dtypes(exclude=object)
X_test_cats_cols = X_test.select_dtypes(include=object)

In [158]:
print(X_train_cats_cols.shape)
print(y_train.shape)

(5634, 17)
(5634,)

In [159]:
X_train_cats_cols.columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim'],
      dtype='object')

In [160]:
nominal_encode = X_train_cats_cols.drop(['Contract','customerID'],axis=1)

In [161]:
nominal_encode.columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'PaperlessBilling',
       'PaymentMethod', 'Sim'],
      dtype='object')

In [162]:
# applying the nominal encoding technique
# applying the one host encoder on gender, partner, dependent for binary data

In [163]:
cat_same = pd.DataFrame()
cat_same['gender'] = X_train_cats_cols['gender']
cat_same['Partner'] = X_train_cats_cols['Partner']
cat_same['Dependents'] = X_train_cats_cols['Dependents']

In [164]:
from sklearn.preprocessing import OneHotEncoder

onehot = OneHotEncoder(drop='first')

In [165]:
onehot.fit(cat_same[['gender','Partner','Dependents']])

OneHotEncoder(drop='first')

In [166]:
val = onehot.transform(cat_same[['gender','Partner','Dependents']]).toarray()

In [167]:
val

array([[0., 1., 1.],
       [0., 1., 0.],
       [0., 0., 0.],
       ...,
       [0., 1., 1.],
       [0., 0., 0.],
       [1., 0., 0.]])

In [168]:
t = pd.DataFrame(val)

t.columns = onehot.get_feature_names_out()

cat_same.reset_index(drop=True,inplace=True)
t.reset_index(drop=True,inplace=True)

In [169]:
cat_same = pd.concat([cat_same,t],axis=1)

In [170]:
cat_same

      gender Partner Dependents  gender_Male  Partner_Yes  Dependents_Yes
0     Female     Yes        Yes          0.0          1.0             1.0
1     Female     Yes         No          0.0          1.0             0.0
2     Female      No         No          0.0          0.0             0.0
3       Male     Yes         No          1.0          1.0             0.0
4     Female     Yes        Yes          0.0          1.0             1.0
...      ...     ...        ...          ...          ...             ...
5629    Male     Yes         No          1.0          1.0             0.0
5630  Female     Yes         No          0.0          1.0             0.0
5631  Female     Yes        Yes          0.0          1.0             1.0
5632  Female      No         No          0.0          0.0             0.0
5633    Male      No         No          1.0          0.0             0.0

[5634 rows x 6 columns]

In [171]:
diff = pd.DataFrame()

In [172]:
X_train_cats_cols.columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim'],
      dtype='object')

In [173]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
oe.fit(X_train_cats_cols[['PhoneService','MultipleLines', 'InternetService',
                         'OnlineSecurity', 'OnlineBackup','DeviceProtection',
                         'TechSupport', 'StreamingTV', 'StreamingMovies',
                          'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim']])

OrdinalEncoder()

In [174]:
oe.categories_

[array(['No', 'Yes'], dtype=object),
 array(['No', 'No phone service', 'Yes'], dtype=object),
 array(['DSL', 'Fiber optic', 'No'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['Month-to-month', 'One year', 'Two year'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Bank transfer (automatic)', 'Credit card (automatic)',
        'Electronic check', 'Mailed check'], dtype=object),
 array(['Airtel', 'BSNL', 'Reliance Jio', 'Vodafone Idea'], dtype=object)]

In [175]:
oe.get_feature_names_out()+'_rep'

array(['PhoneService_rep', 'MultipleLines_rep', 'InternetService_rep',
       'OnlineSecurity_rep', 'OnlineBackup_rep', 'DeviceProtection_rep',
       'TechSupport_rep', 'StreamingTV_rep', 'StreamingMovies_rep',
       'Contract_rep', 'PaperlessBilling_rep', 'PaymentMethod_rep',
       'Sim_rep'], dtype=object)

In [176]:
val = oe.transform(X_train_cats_cols[['PhoneService','MultipleLines', 'InternetService',
                         'OnlineSecurity', 'OnlineBackup','DeviceProtection',
                         'TechSupport', 'StreamingTV', 'StreamingMovies',
                          'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim']])

In [177]:
t1=pd.DataFrame(val)
t1.columns = oe.get_feature_names_out()+'_re'
X_train_cats_cols.reset_index(drop=True,inplace=True)
t1.reset_index(drop=True,inplace=True)

In [178]:
X_train_cats_cols = pd.concat([X_train_cats_cols, t1], axis=1)

In [179]:
X_train_cats_cols.head(5)

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,OnlineSecurity_re,OnlineBackup_re,DeviceProtection_re,TechSupport_re,StreamingTV_re,StreamingMovies_re,Contract_re,PaperlessBilling_re,PaymentMethod_re,Sim_re
0,7839-NUIAA,Female,Yes,Yes,Yes,Yes,DSL,Yes,Yes,No,...,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
1,5829-NVSQN,Female,Yes,No,Yes,No,DSL,Yes,No,Yes,...,2.0,0.0,2.0,2.0,0.0,2.0,1.0,1.0,0.0,0.0
2,0374-IOEGQ,Female,No,No,Yes,No,DSL,No,No,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0
3,2486-WYVVE,Male,Yes,No,Yes,Yes,DSL,No,No,Yes,...,0.0,0.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,0.0
4,6207-WIOLX,Female,Yes,Yes,No,No phone service,DSL,Yes,Yes,Yes,...,2.0,2.0,2.0,0.0,2.0,2.0,0.0,1.0,1.0,0.0

In [180]:
y_train = y_train.map({'Yes':1,'No':0}).astype(int)

In [181]:
from sklearn.preprocessing import  TargetEncoder

te = TargetEncoder()

te.fit(X_train_cats_cols[['PhoneService','MultipleLines', 'InternetService',
                         'OnlineSecurity', 'OnlineBackup','DeviceProtection',
                         'TechSupport', 'StreamingTV', 'StreamingMovies',
                          'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim']], y_train)

TargetEncoder()

In [182]:
te.categories_

[array(['No', 'Yes'], dtype=object),
 array(['No', 'No phone service', 'Yes'], dtype=object),
 array(['DSL', 'Fiber optic', 'No'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['No', 'No internet service', 'Yes'], dtype=object),
 array(['Month-to-month', 'One year', 'Two year'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Bank transfer (automatic)', 'Credit card (automatic)',
        'Electronic check', 'Mailed check'], dtype=object),
 array(['Airtel', 'BSNL', 'Reliance Jio', 'Vodafone Idea'], dtype=object)]

In [183]:
te.get_feature_names_out()+'_tm'

array(['PhoneService_tm', 'MultipleLines_tm', 'InternetService_tm',
       'OnlineSecurity_tm', 'OnlineBackup_tm', 'DeviceProtection_tm',
       'TechSupport_tm', 'StreamingTV_tm', 'StreamingMovies_tm',
       'Contract_tm', 'PaperlessBilling_tm', 'PaymentMethod_tm', 'Sim_tm'],
      dtype=object)

In [184]:
values = te.transform(X_train_cats_cols[['PhoneService','MultipleLines', 'InternetService',
                         'OnlineSecurity', 'OnlineBackup','DeviceProtection',
                         'TechSupport', 'StreamingTV', 'StreamingMovies',
                          'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim']])

In [185]:
t2 = pd.DataFrame(values)

In [186]:
t2.columns = te.get_feature_names_out()+'_tm'
X_train_cats_cols.reset_index(drop=True, inplace=True)
t2.reset_index(drop=True, inplace=True)

In [187]:
X_train_cats_cols = pd.concat([X_train_cats_cols,t2],axis=1)

In [188]:
X_train_cats_cols

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,...,OnlineSecurity_tm,OnlineBackup_tm,DeviceProtection_tm,TechSupport_tm,StreamingTV_tm,StreamingMovies_tm,Contract_tm,PaperlessBilling_tm,PaymentMethod_tm,Sim_tm
0,7839-NUIAA,Female,Yes,Yes,Yes,Yes,DSL,Yes,Yes,No,...,0.150944,0.220535,0.400016,0.418488,0.336123,0.337019,0.428691,0.164671,0.449021,0.186535
1,5829-NVSQN,Female,Yes,No,Yes,No,DSL,Yes,No,Yes,...,0.150944,0.402610,0.220970,0.158456,0.336123,0.306966,0.121978,0.341212,0.179037,0.186535
2,0374-IOEGQ,Female,No,No,Yes,No,DSL,No,No,No,...,0.421155,0.402610,0.400016,0.418488,0.336123,0.337019,0.428691,0.164671,0.449021,0.186535
3,2486-WYVVE,Male,Yes,No,Yes,Yes,DSL,No,No,Yes,...,0.421155,0.402610,0.220970,0.158456,0.307850,0.306966,0.121978,0.341212,0.194490,0.186535
4,6207-WIOLX,Female,Yes,Yes,No,No phone service,DSL,Yes,Yes,Yes,...,0.150944,0.220535,0.220970,0.418488,0.307850,0.306966,0.428691,0.341212,0.153846,0.186535
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5629,2956-GGUCQ,Male,Yes,No,Yes,Yes,Fiber optic,Yes,No,No,...,0.150944,0.402610,0.400016,0.418488,0.336123,0.337019,0.428691,0.341212,0.449021,0.428607
5630,8707-RMEZH,Female,Yes,No,Yes,No,Fiber optic,Yes,Yes,No,...,0.150944,0.220535,0.400016,0.418488,0.336123,0.306966,0.121978,0.164671,0.153846,0.428607
5631,5685-IIXLY,Female,Yes,Yes,Yes,No,Fiber optic,No,Yes,No,...,0.421155,0.220535,0.400016,0.418488,0.336123,0.306966,0.428691,0.341212,0.449021,0.428607
5632,9633-XQABV,Female,No,No,Yes,No,Fiber optic,No,No,No,...,0.421155,0.402610,0.400016,0.418488,0.336123,0.337019,0.428691,0.341212,0.449021,0.428607
5633,4488-PSYCG,Male,No,No,Yes,No,No,No internet service,No internet service,No internet service,...,0.076411,0.076411,0.076411,0.076411,0.076411,0.076411,0.428691,0.164671,0.179037,0.091961

In [189]:
X_train_cats_cols.columns

Index(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService',
       'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
       'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies',
       'Contract', 'PaperlessBilling', 'PaymentMethod', 'Sim',
       'PhoneService_re', 'MultipleLines_re', 'InternetService_re',
       'OnlineSecurity_re', 'OnlineBackup_re', 'DeviceProtection_re',
       'TechSupport_re', 'StreamingTV_re', 'StreamingMovies_re', 'Contract_re',
       'PaperlessBilling_re', 'PaymentMethod_re', 'Sim_re', 'PhoneService_tm',
       'MultipleLines_tm', 'InternetService_tm', 'OnlineSecurity_tm',
       'OnlineBackup_tm', 'DeviceProtection_tm', 'TechSupport_tm',
       'StreamingTV_tm', 'StreamingMovies_tm', 'Contract_tm',
       'PaperlessBilling_tm', 'PaymentMethod_tm', 'Sim_tm'],
      dtype='object')

In [190]:
X_train_cats_cols.shape

(5634, 43)

In [191]:
Training_data = pd.concat()

TypeError: concat() missing 1 required positional argument: 'objs'